"""Independent critical-review checks, not the author's replay.

Horn rows are generated by counting Littlewood-Richardson tableaux, rather
than by the recursive Horn admissibility generator used in horn.py.
"""
from functools import lru_cache
from itertools import combinations, product
from fractions import Fraction as Q
from pathlib import Path
import json
import sympy as s

@lru_cache(None)
def lr(left, content, outer):
    r=len(outer)
    if any(a>c for a,c in zip(left,outer)) or sum(left)+sum(content)!=sum(outer): return 0
    cells=[(i,j) for i in range(r) for j in range(outer[i]-1,left[i]-1,-1)]
    vals={}
    used=[0]*r
    def fill(pos):
        if pos==len(cells): return int(tuple(used)==content)
        i,j=cells[pos]
        total=0
        for v in range(r):
            if used[v]==content[v]: continue
            if (i,j+1) in vals and v>vals[(i,j+1)]: continue
            if (i-1,j) in vals and v<=vals[(i-1,j)]: continue
            used[v]+=1
            if all(used[t]>=used[t+1] for t in range(r-1)):
                vals[(i,j)]=v
                total+=fill(pos+1)
                del vals[(i,j)]
            used[v]-=1
        return total
    return fill(0)

def part(subset):
    return tuple(i-j for i,j in zip(reversed(subset),range(len(subset),0,-1)))

common=(Q(3,4),Q(5,12),Q(1,6),Q(0),Q(0))
negative=tuple(-x for x in reversed(common))
target=(Q(3,4),Q(1,4),Q(-1,6),Q(-5,12),Q(-5,12))
rows=[]
counts={}
for r in range(1,5):
    count=0
    sets=list(combinations(range(1,6),r))
    for first,second,third in product(sets,repeat=3):
        coefficient=lr(part(first),part(second),part(third))
        if not coefficient: continue
        slack=sum(common[i-1] for i in first)+sum(negative[j-1] for j in second)-sum(target[k-1] for k in third)
        assert slack>=0,(first,second,third,slack)
        rows.append({'I':first,'J':second,'K':third,'LR_coefficient':coefficient,'slack':str(slack)})
        count+=1
    counts[r]=count
assert len(rows)==142,len(rows)
assert sum(target)==0 and sum(common)==Q(4,3)

k,l,n=s.symbols('k l n')
q=2-1/k-1/n
c1=(k+l)*(k+l-1)/(2*k*l)
B=k*k*l-2*k*k*n+k*k-k*l*n+k*l+k*n+l*n
identity=2*q*((n+1)/2-c1)-(n-k)*(2-1/k-l/n)+(k-1)*(l-1)/(k*k*l*n)*B
assert s.factor(identity)==0
assert s.expand(B.subs(l,1)+ (2*k*k-1)*(n-1)-k-1)==0
assert s.expand(B.subs(l,n)+(k+n)*(k*n-k-n))==0

# Independent transport primal/dual values.
cost=((Q(1),Q(3,2),Q(2)),(Q(3,2),Q(1),Q(5,3)))
alpha=(Q(1,2),Q(1,2)); beta=(Q(0),Q(1,2),Q(1,2))
plan=((Q(0),Q(0),Q(1,2)),(Q(0),Q(1,2),Q(0)))
u=(Q(1,2),Q(0)); v=(Q(1,2),Q(1),Q(3,2))
assert all(sum(plan[i])==alpha[i] for i in range(2))
assert all(sum(plan[i][j] for i in range(2))==beta[j] for j in range(3))
assert all(u[i]+v[j]<=cost[i][j] for i in range(2) for j in range(3))
primal=sum(plan[i][j]*cost[i][j] for i in range(2) for j in range(3))
dual=sum(x*y for x,y in zip(alpha,u))+sum(x*y for x,y in zip(beta,v))
product_bound=sum(alpha[i]*beta[j]*cost[i][j] for i in range(2) for j in range(3))
assert primal==dual==Q(3,2) and product_bound==Q(37,24)
report={'status':'all exact independent checks passed','Horn_generation':'Littlewood-Richardson skew-tableau counting','Horn_counts_by_subset_size':counts,'Horn_total':len(rows),'Horn_min_slack':str(min(Q(x['slack']) for x in rows)),'atom_identity_exact':True,'endpoint_polynomial_identities_exact':True,'transport_primal':str(primal),'transport_dual':str(dual),'product_bound':str(product_bound),'matrix_cost_lower_and_Horn_upper':str(sum(common)),'Horn_rows':rows}
Path(__file__).with_name('independent_review_certificate.json').write_text(json.dumps(report,indent=2)+'\n')
print({key:value for key,value in report.items() if key!='Horn_rows'})
