"""Independent intake cannot cross ownership, publication or originality boundaries."""
import hashlib
import io
import json
from pathlib import Path
import unittest
from datetime import timedelta
from unittest.mock import patch

import test_intake as fixtures
from services.intake.app import get_db, iso, now, init_db
from services.intake.independent_agents import ACKS, POLICY
from services.intake import originality

PDF = b'%PDF-1.7\nindependent test manuscript'


class IndependentAgentTests(unittest.TestCase):
    def setUp(self):
        fixtures.IntakeTests.setUp(self)
        self.app.config['INDEPENDENT_AGENTS_ENABLED'] = True
        self.api = self.app.test_client()

    def tearDown(self):
        self.temp.cleanup()

    def register(self):
        result = self.api.post('/api/v1/independent-agents', json={'agent_name': 'Orion', 'agent_version': 'test-1',
            'purpose': 'Deposit a self-declared agent contribution for editorial checks.',
            'policy_version': POLICY, 'acknowledgements': {key: True for key in ACKS}})
        self.assertEqual(result.status_code, 201, result.data)
        return result.json

    def upload(self, agent, key='same-manuscript-1', metadata=None, pdf=PDF):
        value = {'title': 'A self-declared research contribution', 'abstract': 'An explicit account of reproducible research. ' * 4,
                 'public_credit': 'agent_alias', 'primary_subject': 'airr-quantum-information', 'secondary_subjects': [],
                 'specific_topic': '', 'sha256': hashlib.sha256(PDF).hexdigest(),
                 'source_disclosure': 'Generated by the declared test agent. No external text is claimed as original. Sources and rights must be checked by the editor.',
                 'operator_conflict': False, 'publication_requested': True, 'requested_license': 'CC-BY-4.0', 'revision_of': None}
        value.update(metadata or {})
        with patch('services.intake.app.scan_file', return_value=('clean', 'Approved scanner reported clean.')):
            return self.api.post('/api/v1/independent-agents/submissions', headers={'Authorization': 'Bearer ' + agent['token'], 'Idempotency-Key': key},
                data={'metadata': json.dumps(value), 'manuscript': (io.BytesIO(pdf), 'paper.pdf')})

    def editor(self):
        with self.client.session_transaction() as session:
            session['user_id'] = 2
            session['csrf_token'] = 'editor-csrf'
        return 'editor-csrf'

    def test_private_no_email_no_human_attestation_and_hashed_token(self):
        agent = self.register()
        response = self.upload(agent)
        self.assertEqual(response.status_code, 201, response.data)
        case_id = response.json['registration_number']
        self.assertIsNone(response.json['public_release_url'])
        with self.app.app_context():
            db = get_db()
            row = db.execute('SELECT * FROM independent_agents').fetchone()
            self.assertNotEqual(row['token_hash'], agent['token'])
            paper = db.execute('SELECT * FROM submissions WHERE id=?', (case_id,)).fetchone()
            self.assertEqual(paper['submission_channel'], 'independent_agent')
            self.assertEqual(paper['authors'], 'Agent: Orion')
            self.assertEqual(paper['originality_required'], 1)
            self.assertEqual(paper['terms_version'], POLICY)
            self.assertEqual(paper['publication_mode'], 'independent_agent')
            self.assertFalse(originality.ready(db, paper))
            self.assertEqual(db.execute('SELECT COUNT(*) FROM mail_outbox').fetchone()[0], 0)
            self.assertEqual(db.execute('SELECT COUNT(*) FROM publication_permissions').fetchone()[0], 0)
            self.assertEqual(db.execute('SELECT COUNT(*) FROM model_reviews').fetchone()[0], 0)

    def test_isolation_and_cookie_not_token(self):
        one, two = self.register(), self.register()
        case_id = self.upload(one).json['registration_number']
        path = '/api/v1/independent-agents/cases/' + case_id
        self.assertEqual(self.api.get(path, headers={'Authorization': 'Bearer ' + two['token']}).status_code, 404)
        self.assertEqual(self.client.get(path).status_code, 401)
        result = self.api.get(path, headers={'Authorization': 'Bearer ' + one['token']})
        self.assertEqual(result.status_code, 200)
        self.assertNotIn('token', result.json)
        self.assertNotIn('originality_scans', result.json)
        self.assertEqual(self.api.get('/admin/submission/' + case_id, headers={'Authorization': 'Bearer ' + one['token']}).status_code, 302)

    def test_retries_verify_pdf_and_do_not_duplicate_or_use_quota(self):
        agent = self.register()
        first = self.upload(agent)
        self.assertEqual(first.status_code, 201)
        self.assertEqual(self.upload(agent).json['registration_number'], first.json['registration_number'])
        self.assertEqual(self.upload(agent, pdf=PDF + b'changed').status_code, 409)
        self.assertEqual(self.upload(agent, metadata={'title': 'Different'}).status_code, 409)
        with self.app.app_context():
            self.assertEqual(get_db().execute('SELECT COUNT(*) FROM submissions').fetchone()[0], 1)

    def test_closed_intake_and_revoked_tokens(self):
        agent = self.register()
        self.app.config['INTAKE_OPEN'] = False
        self.assertEqual(self.upload(agent).status_code, 503)
        self.assertEqual(self.api.get('/api/v1/independent-agents/me', headers={'Authorization': 'Bearer ' + agent['token']}).status_code, 200)
        self.assertEqual(self.api.post('/api/v1/independent-agents/revoke', headers={'Authorization': 'Bearer ' + agent['token']}).status_code, 200)
        self.assertEqual(self.api.get('/api/v1/independent-agents/me', headers={'Authorization': 'Bearer ' + agent['token']}).status_code, 401)

    def test_originality_required_for_anonymous_humans_and_migration_preserves_cases(self):
        helper = fixtures.IntakeTests('runTest')
        helper.__dict__.update(self.__dict__)
        case_id = helper.upload(fields={'authors': ''})
        with self.app.app_context():
            init_db()
            row = get_db().execute('SELECT * FROM submissions WHERE id=?', (case_id,)).fetchone()
            self.assertEqual(row['originality_required'], 1)
            self.assertFalse(originality.ready(get_db(), row))

    def test_all_release_paths_block_until_evidenced_exact_hash_review(self):
        agent = self.register()
        case_id = self.upload(agent).json['registration_number']
        csrf = self.editor()
        url = '/admin/submission/' + case_id
        self.assertEqual(self.client.get(url).status_code, 200)
        self.assertEqual(self.client.get(url + '/release-package').status_code, 409)
        form = {'csrf_token': csrf, 'signed': 'on', 'sha256': hashlib.sha256(PDF).hexdigest(),
                'permission_evidence': 'Recorded inspectable distribution evidence for this test manuscript and license. This is a synthetic test record, not a real grant.'}
        self.assertEqual(self.client.post(url + '/agent-release', data=form).status_code, 409)
        with self.app.app_context():
            db = get_db()
            scan = db.execute('INSERT INTO originality_scans(submission_id,manuscript_sha256,result_json,created_by,created_at) VALUES(?,?,?,?,?)',
                              (case_id, form['sha256'], '{}', 2, iso()))
            scan_id = scan.lastrowid
            db.commit()
        evidence = {k: 'Documented synthetic test evidence covering this check in full.' for k in
                    ('search_scope', 'match_adjudication', 'attribution_basis', 'rights_basis', 'privacy_check')}
        review = {**form, **evidence, 'sources_checked': 'https://example.org/source checked in this synthetic test; attribution was examined.', 'scan_id': str(scan_id), 'outcome': 'clear'}
        self.assertEqual(self.client.post(url + '/originality-review', data={**review, 'sha256': '0' * 64}).status_code, 409)
        self.assertEqual(self.client.post(url + '/originality-review', data=review).status_code, 302)
        # A permission accidentally issued through another workflow cannot stand
        # in for this route's evidenced human distribution decision.
        with self.app.app_context():
            db = get_db()
            db.execute('INSERT INTO publication_permissions VALUES(?,?,?,?)', (case_id, form['sha256'], 'CC-BY-4.0', iso()))
            db.commit()
        self.assertEqual(self.client.get(url + '/release-package').status_code, 409)
        with self.app.app_context():
            get_db().execute('DELETE FROM publication_permissions WHERE submission_id=?', (case_id,))
            get_db().commit()
        self.assertEqual(self.client.post(url + '/agent-release', data=form).status_code, 302)
        result = self.client.get(url + '/release-package')
        self.assertEqual(result.status_code, 200, result.data)
        self.assertEqual(result.json['public_status'], 'working_paper')
        self.assertEqual(result.json['originality_review']['manuscript_sha256'], form['sha256'])
        self.assertEqual(self.client.post(url + '/originality-review', data={**review, 'outcome': 'concerns'}).status_code, 302)
        self.assertEqual(self.client.get(url + '/release-package').status_code, 409)
        command = self.app.test_cli_runner().invoke(args=['mark-published', case_id, 'https://example.org/version'])
        self.assertNotEqual(command.exit_code, 0)

    def test_similarity_flags_reformatted_copy_without_automatic_verdict(self):
        corpus = Path(self.temp.name) / 'corpus' / 'ARR-TEST'
        corpus.mkdir(parents=True)
        prose = ' '.join('word' + str(i) for i in range(90))
        (corpus / 'paper.txt').write_text(prose)
        result = originality.compare_text(prose.upper().replace(' ', '\n'), corpus.parent)
        self.assertEqual(result['matches'][0]['candidate_sequence_overlap'], 1.0)
        self.assertIn('not a plagiarism verdict', result['scope'])
        with self.assertRaises(ValueError):
            originality.compare_text(prose, corpus / 'missing')

    def clear_originality(self, case_id):
        csrf = self.editor()
        corpus = Path(self.temp.name) / 'corpus' / 'public'
        corpus.mkdir(parents=True, exist_ok=True)
        prose = ' '.join('word' + str(i) for i in range(90))
        (corpus / 'paper.txt').write_text(prose)
        self.app.config['ORIGINALITY_CORPUS'] = str(corpus.parent)
        url = '/admin/submission/' + case_id
        with patch('services.intake.originality.extract_text', return_value=prose):
            result = self.client.post(url + '/originality-scan', data={'csrf_token': csrf})
        self.assertEqual(result.status_code, 302, result.data)
        with self.app.app_context():
            db = get_db()
            scan = db.execute('SELECT * FROM originality_scans WHERE submission_id=? ORDER BY id DESC LIMIT 1', (case_id,)).fetchone()
            self.assertFalse(originality.ready(db, db.execute('SELECT * FROM submissions WHERE id=?', (case_id,)).fetchone()))
            scan_id, sha = scan['id'], scan['manuscript_sha256']
        review = {'csrf_token': csrf, 'sha256': sha, 'scan_id': scan_id, 'outcome': 'clear', 'signed': 'on',
                  **{k: 'Documented synthetic test evidence, not a real scientific or rights determination.' for k in
                    ('search_scope', 'match_adjudication', 'attribution_basis', 'rights_basis', 'privacy_check')},
                  'sources_checked': 'https://example.org/source is the synthetic source for this fixture.'}
        self.assertEqual(self.client.post(url + '/originality-review', data=review).status_code, 302)
        return review

    def test_anonymous_handoff_hides_identity_and_new_scan_invalidates_clearance(self):
        agent = self.register()
        case_id = self.upload(agent, metadata={'public_credit':'anonymous'}).json['registration_number']
        review = self.clear_originality(case_id)
        url = '/admin/submission/' + case_id
        self.assertEqual(self.client.post(url + '/agent-release', data={**review,
            'permission_evidence':'Inspectable synthetic rights evidence covers this PDF and requested license. This is a test, not an actual authorization.'}).status_code,302)
        handoff = self.client.get(url + '/release-package').json
        self.assertEqual(handoff['authors'], 'Anonymous')
        self.assertNotIn('Orion', json.dumps(handoff))
        self.assertNotIn(agent['agent_id'], json.dumps(handoff))
        self.assertNotIn('version', handoff['agent_provenance'])
        self.assertIs(handoff['agent_provenance']['identity_verified'], False)
        with patch('services.intake.originality.extract_text', return_value=' '.join('word' + str(i) for i in range(90))):
            self.assertEqual(self.client.post(url + '/originality-scan', data={'csrf_token': review['csrf_token']}).status_code,302)
        self.assertEqual(self.client.get(url + '/release-package').status_code,409)
        self.assertEqual(self.client.post(url + '/originality-review',data=review).status_code,409)

    def test_failed_extraction_does_not_create_a_check(self):
        case_id = self.upload(self.register()).json['registration_number']
        csrf = self.editor()
        with patch('services.intake.originality.extract_text',side_effect=ValueError('No readable text.')):
            self.assertEqual(self.client.post('/admin/submission/'+case_id+'/originality-scan',data={'csrf_token':csrf}).status_code,409)
        with self.app.app_context():
            self.assertEqual(get_db().execute('SELECT COUNT(*) FROM originality_scans').fetchone()[0],0)

    def test_new_revision_requires_fresh_clearance_and_owns_parent(self):
        agent, other = self.register(), self.register()
        case_id = self.upload(agent).json['registration_number']
        self.clear_originality(case_id)
        with self.app.app_context():
            get_db().execute("UPDATE submissions SET status='changes_requested' WHERE id=?",(case_id,))
            get_db().commit()
        self.assertEqual(self.upload(other,metadata={'revision_of':case_id}).status_code,404)
        revised = PDF+b' revised'
        response = self.upload(agent,key='corrected-version-2',pdf=revised,metadata={'revision_of':case_id,'sha256':hashlib.sha256(revised).hexdigest()})
        self.assertEqual(response.status_code,201,response.data)
        with self.app.app_context():
            db=get_db()
            row=db.execute('SELECT * FROM submissions WHERE id=?',(response.json['registration_number'],)).fetchone()
            self.assertEqual(row['parent_id'],case_id)
            self.assertEqual(row['revision_number'],2)
            self.assertFalse(originality.ready(db,row))
            self.assertEqual(db.execute('SELECT COUNT(*) FROM publication_permissions WHERE submission_id=?',(row['id'],)).fetchone()[0],0)

    def test_token_rotation_expiry_and_quota(self):
        agent=self.register()
        headers={'Authorization':'Bearer '+agent['token']}
        replacement=self.api.post('/api/v1/independent-agents/token',headers=headers)
        self.assertEqual(replacement.status_code,200)
        self.assertEqual(self.api.get('/api/v1/independent-agents/me',headers=headers).status_code,401)
        agent['token']=replacement.json['token']
        self.assertEqual(self.upload(agent,key='first-upload').status_code,201)
        self.assertEqual(self.upload(agent,key='second-upload').status_code,201)
        self.assertEqual(self.upload(agent,key='third-upload').status_code,429)
        with self.app.app_context():
            get_db().execute('UPDATE independent_agents SET expires_at=?',(iso(now()-timedelta(days=1)),))
            get_db().commit()
        self.assertEqual(self.api.get('/api/v1/independent-agents/me',headers={'Authorization':'Bearer '+agent['token']}).status_code,401)

    def test_malformed_metadata_and_production_gate(self):
        agent=self.register()
        self.assertEqual(self.upload(agent,metadata={'requested_license':[]}).status_code,400)
        self.assertEqual(self.upload(agent,metadata={'publication_requested':'true'}).status_code,400)
        self.app.config.update(TESTING=False,LAUNCH_APPROVAL_FILE='missing.json')
        self.assertFalse(self.api.get('/api/v1/independent-agents/policy').json['intake_open'])
        self.assertEqual(self.upload(agent).status_code,503)

    def test_private_evidence_erased_but_minimal_review_outcome_preserved(self):
        case_id=self.upload(self.register()).json['registration_number']
        self.clear_originality(case_id)
        with self.app.app_context():
            get_db().execute("UPDATE submissions SET status='withdrawn',delete_after=? WHERE id=?",(iso(now()-timedelta(days=1)),case_id))
            get_db().commit()
        result=self.app.test_cli_runner().invoke(args=['retention-sweep'])
        self.assertEqual(result.exit_code,0,result.output)
        with self.app.app_context():
            db=get_db()
            row=db.execute('SELECT * FROM submissions WHERE id=?',(case_id,)).fetchone()
            self.assertEqual(row['source_disclosure'],'')
            self.assertEqual(db.execute('SELECT evidence_json FROM originality_reviews').fetchone()[0],'{}')
            self.assertEqual(db.execute('SELECT result_json FROM originality_scans').fetchone()[0],'{}')
            self.assertTrue(originality.ready(db,row))

    def test_case_actions_plan_scope_and_independent_appeal(self):
        agent=self.register()
        case_id=self.upload(agent,metadata={'publication_requested':False}).json['registration_number']
        path='/api/v1/independent-agents/cases/'+case_id+'/actions'
        headers={'Authorization':'Bearer '+agent['token']}
        def act(value):
            return self.api.post(path,headers=headers,json=value)
        self.assertEqual(act({'action':'publish'}).status_code,400)
        self.assertEqual(act({'action':'reply','body':'A private response supplying more evidence for this paper.'}).status_code,200)
        self.assertEqual(act({'action':'request_publication','sha256':hashlib.sha256(PDF).hexdigest(),'requested_license':'CC-BY-4.0'}).status_code,200)
        with self.app.app_context():
            db=get_db()
            plan=db.execute('INSERT INTO assessment_plans(submission_id,manuscript_sha256,providers_json,notice,created_by,created_at) VALUES(?,?,?,?,?,?)',
                (case_id,hashlib.sha256(PDF).hexdigest(),'[{"provider":"fixture","model_id":"fixture"}]','A synthetic named provider plan and safeguards for this exact test PDF.',2,iso()))
            plan_id=plan.lastrowid
            db.commit()
        approval={'action':'authorize_plan','plan_id':plan_id,'sha256':hashlib.sha256(PDF).hexdigest(),'confirm':True}
        self.assertEqual(act(approval).status_code,409)
        self.clear_originality(case_id)
        self.assertEqual(act({**approval,'sha256':'0'*64}).status_code,409)
        self.assertEqual(act(approval).status_code,200)
        with self.app.app_context():
            db=get_db()
            db.execute("UPDATE submissions SET status='declined',decided_at=?,decision_by=2 WHERE id=?",(iso(),case_id))
            db.commit()
        self.assertEqual(act({'action':'appeal','body':'A specific evidenced challenge to this synthetic test decision.'}).status_code,200)
        self.assertEqual(act({'action':'appeal','body':'A second appeal must not replace the first evidenced challenge.'}).status_code,409)
        with self.app.app_context():
            self.assertEqual(get_db().execute('SELECT status FROM submissions WHERE id=?',(case_id,)).fetchone()[0],'appeal_pending')
            self.assertEqual(get_db().execute('SELECT COUNT(*) FROM publication_permissions').fetchone()[0],0)


if __name__ == '__main__':
    unittest.main()
