"""E3: independent exact certification of the statement (not the proof) for p = 7, l = 4, the first case not
covered by earlier results (l<=3: 0WE Cor 2.1 + Chebotarev; l = p-1: trivial bound).
For each AGL(2,7)-orbit representative S = {g0,g1,g2,g3} we certify that no C = W_{g0} + c1 W_{g1} + c2 W_{g2} + c3 W_{g3}
has rank <= 3 (nullity >= 4), i.e. that the ideal generated by Phi_7(w) and the 4x4 minors of C (polynomials in
c1,c2,c3,w over Q) is the unit ideal (Groebner basis {1}). Setting c0 = 1 is WLOG because a zero coefficient
reduces to a smaller support (already covered). Generators are added in random batches until the basis is {1}
or the batch limit is reached (then the result is reported as 'not certified', which is not a counterexample).
"""
import sympy as sp, itertools, random, sys, time

def run(p, S, batches=6, batch=40, seed=1):
    w = sp.symbols('w'); cs = sp.symbols(f'c1:{len(S)}')
    coeffs = [sp.Integer(1)] + list(cs)
    # W_{a,b}[j,k] = w^{b k} [j = k+a] ; entries as polynomials in w (exponents reduced mod p)
    C = sp.zeros(p, p)
    for (a, b), c in zip(S, coeffs):
        for k in range(p):
            C[(k+a) % p, k] += c * w**((b*k) % p)
    Phi = sum(w**i for i in range(p))
    r = p - len(S) + 1          # rank must be >= r ; certify no point with all r x r minors zero
    rows = list(itertools.combinations(range(p), r)); cols = list(itertools.combinations(range(p), r))
    allminors = [(R, Cc) for R in rows for Cc in cols]
    random.seed(seed); random.shuffle(allminors)
    gens = [Phi]
    t0 = time.time()
    for bi in range(batches):
        chunk = allminors[bi*batch:(bi+1)*batch]
        for R, Cc in chunk:
            m = sp.expand(C.extract(list(R), list(Cc)).det(method='berkowitz'))
            m = sp.rem(sp.Poly(m, w), sp.Poly(Phi, w)).as_expr() if m != 0 else m
            if m != 0: gens.append(sp.expand(m))
        G = sp.groebner(gens, *cs, w, order='grevlex', domain='QQ')
        if list(G.exprs) == [1]:
            return True, bi+1, len(gens), time.time()-t0
    return False, batches, len(gens), time.time()-t0

if __name__ == '__main__':
    p = 7
    reps = [[(0,0),(1,0),(0,1),(0,2)], [(0,0),(1,0),(0,1),(0,3)], [(0,0),(1,0),(0,1),(1,1)], [(0,0),(1,0),(0,1),(1,2)],
            [(0,0),(1,0),(0,1),(2,2)], [(0,0),(1,0),(0,1),(3,6)], [(0,0),(1,0),(2,0),(3,0)], [(0,0),(1,0),(2,0),(4,0)]]
    for S in reps:
        ok, nb, ng, dt = run(p, S)
        print(f"p=7 l=4 S={S}: {'CERTIFIED rank>=4 (Groebner basis = {1})' if ok else 'NOT certified within batch limit'} "
              f"batches={nb} generators={ng} time={dt:.1f}s", flush=True)
