from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,zipfile,subprocess,sys,os,copy
h=Path(__file__).resolve().parents[1];e=h/'outputs/extension-importados-20260912';pid='ARR-2026-07EH3CZRD89YC8JN';out=h/'work/calibration-validator-correction-3';old=h/'work/calibration-validator-correction-2/verify_calibration_memory.py';p=out/'verify_calibration_memory.py';runner=out/'run_validator.py';cases=out/'cases';sha=lambda b:hashlib.sha256(b).hexdigest();enc=lambda v:(json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode();assert not (out/'RESULT.json').exists();inputs=[]
with zipfile.ZipFile(e/pid/'candidate-v2-preassessment-input.zip') as z:original=z.read('scientific-source/results/calibration_memory/certificate.json')
assert sha(original)=='2d4b7bb2ad72209df21299198ef56952d247191c333baec1b6509ba8a52f9230';assert json.loads(original)==json.loads((cases/'reviewer-preserved_original.json').read_bytes())
for path in sorted(cases.glob('reviewer-*.json')):
    if path.stem!='reviewer-preserved_original':inputs.append((path,path.stem=='reviewer-own_replay','Native reviewer fixture, bytes unchanged; validator execution only.'))
original_path=cases/'exact-preserved-original.json';original_path.write_bytes(original);inputs.append((original_path,True,'Exact original scientific ledger bytes from the pinned candidate input. Reviewer serialized fixture has equal JSON but different whitespace; original byte identity used here.'))
previous=json.loads((h/'work/calibration-validator-correction-2/RESULT.json').read_bytes())
for r in previous['records']:
    if not r['expected_accept']:
        pp=cases/('prior-'+r['name']+'.json');raw=(h/'work/calibration-validator-correction-2'/(r['name']+'.json')).read_bytes();assert sha(raw)==r['input_sha256'];pp.write_bytes(raw);inputs.append((pp,False,'Previously preserved mutation, unchanged.'))
base=(e/pid/'local-original-audit/certificate-new.json').read_bytes();pp=cases/'coordinator-replay.json';pp.write_bytes(base);inputs.append((pp,True,'Coordinator generator replay from11:24UTC; not a new generator execution.'))
records=[];env=os.environ.copy();env['PYTHONDONTWRITEBYTECODE']='1';start=datetime.now(timezone.utc).isoformat()
for path,expected,origin in inputs:
    cmd=[sys.executable,'-X','utf8',str(runner),str(p),str(path)];t=datetime.now(timezone.utc).isoformat();r=subprocess.run(cmd,cwd=out,env=env,capture_output=True,timeout=30);stem=path.stem;(out/(stem+'.stdout')).write_bytes(r.stdout);(out/(stem+'.stderr')).write_bytes(r.stderr);records.append({'name':stem,'argv':cmd,'started_at':t,'ended_at':datetime.now(timezone.utc).isoformat(),'exit_code':r.returncode,'expected_accept':expected,'accepted':r.returncode==0,'input_sha256':sha(path.read_bytes()),'origin':origin});assert (r.returncode==0)==expected,(stem,r.stderr.decode())
positive=[r['input_sha256'] for r in records if r['expected_accept']];assert len(positive)==len(set(positive))==3
j={'started_at':start,'ended_at':datetime.now(timezone.utc).isoformat(),'python':sys.version,'previous_validator_sha256':sha(old.read_bytes()),'corrected_validator_sha256':sha(p.read_bytes()),'records':records,'positive_input_hashes':positive,'preparation_failures':['Initial source-pin assertion had an extra leading 2; actual d64f08... pin verified against preserved RESULT.json before proceeding.','Reviewer preserved-original fixture reserializes the original JSON. Initial raw-hash assertion failed; semantic equality checked, then exact original bytes extracted from the pinned candidate for the actual positive execution.'],'scope':'Three distinct positive ledger byte identities and32negative fixtures. New validator subprocess executions only, not new generator runs, interval certification or authentication of data origin. Previous positive controls were two calls on identical bytes, and are preserved unchanged. Adds exact fixed-stop formula and elementary Rouche extrema consistency.'};(out/'RESULT.json').write_bytes(enc(j));print(json.dumps({'controls':len(records),'positive_distinct':len(positive),'negative':sum(not r['expected_accept'] for r in records),'validator_sha256':j['corrected_validator_sha256']}))
