"""Exact finite replay for quantum_weyl_trinomials.md.

All mathematical decisions use exact integers, cyclotomic rings or algebraic
number fields. The manuscript, rather than
these finite samples, quantifies over arbitrary dimensions and coefficients.
Run from any directory; the certificate is written beside this source.
"""
from collections import Counter
from itertools import combinations, product
from math import gcd
from pathlib import Path
import hashlib
import json
import platform
import time

import sympy as sp
from composite_matrix_checks import run_checks as composite_checks


def subgroup_size(d, u, v):
    """Index of the integer lattice generated by u,v,d*e1,d*e2."""
    a, b = u
    c, e = v
    index = gcd(d*d, d*a, d*b, d*c, d*e, a*e-b*c)
    return d*d // index


def enumerate_subgroup(d, u, v):
    return {((m*u[0]+n*v[0]) % d, (m*u[1]+n*v[1]) % d)
            for m, n in product(range(d), repeat=2)}


def central_arithmetic():
    records = []
    for d in (2, 3, 4, 5, 7, 8, 9, 16, 25, 27, 32):
        labels = [u for u in product(range(d), repeat=2) if u != (0, 0)]
        counts = Counter()
        explicit = 0
        for u, v in product(labels, repeat=2):
            if u == v:
                continue
            determinant = (u[0]*v[1]-u[1]*v[0]) % d
            q = d // gcd(d, determinant)
            if q == 1:
                continue
            qu = tuple(q*x % d for x in u)
            qv = tuple(q*x % d for x in v)
            r_order = subgroup_size(d, qu, qv)
            assert r_order == d//q, (d, u, v, q, r_order)
            assert subgroup_size(d, u, v) == d*q
            if d <= 8:
                assert len(enumerate_subgroup(d, qu, qv)) == r_order
                explicit += 1
            counts[f"q={q}; central_order={r_order}"] += 1
        records.append({"d": d, "noncommuting_ordered_pairs": sum(counts.values()),
                        "classes": dict(counts),
                        "independent_explicit_subgroup_enumerations": explicit})
        print("central arithmetic", d, sum(counts.values()), flush=True)
    return records


def universal_arithmetic():
    """All distinct relative supports through d=20, including q=1."""
    records = []
    for d in range(2,21):
        labels = [x for x in product(range(d),repeat=2) if x != (0,0)]
        classes = Counter()
        primitive = 0
        for u,v in product(labels,repeat=2):
            if u == v:
                continue
            delta = u[0]*v[1]-u[1]*v[0]
            g = gcd(d,delta)
            q = d//g
            H = subgroup_size(d,u,v)
            h = subgroup_size(d,tuple(q*x % d for x in u),tuple(q*x % d for x in v))
            assert H == q*q*h and d % (q*h) == 0
            m = d//(q*h)
            assert m == gcd(g,*u,*v,delta//g)
            if gcd(d,*u,*v) == 1:
                assert m == 1
                primitive += 1
            classes[f'q={q}; h={h}; m={m}'] += 1
        records.append({'d':d,'ordered_distinct_nonzero_support_pairs':sum(classes.values()),
                        'collectively_primitive_pairs':primitive,'classes':dict(classes)})
    print('universal arithmetic supports',sum(x['ordered_distinct_nonzero_support_pairs'] for x in records),flush=True)
    return records


class Cyclotomic:
    """Integer arithmetic in Z[z]/Phi_q(z)."""
    def __init__(self, q):
        z = sp.Symbol("z")
        self.mod = tuple(int(c) for c in reversed(sp.Poly(sp.cyclotomic_poly(q, z), z).all_coeffs()))
        self.q, self.n = q, len(self.mod)-1
        self.zero = (0,)*self.n
        self.one = (1,)+(0,)*(self.n-1)

    def reduce(self, vals):
        out = list(vals)+[0]*max(0, self.n-len(vals))
        for k in range(len(out)-1, self.n-1, -1):
            c = out[k]
            if c:
                for j in range(self.n):
                    out[k-self.n+j] -= c*self.mod[j]
        return tuple(out[:self.n])

    def root(self, k):
        k %= self.q
        return self.reduce([0]*k+[1])

    def add(self, a, b):
        return tuple(x+y for x, y in zip(a, b))

    def neg(self, a):
        return tuple(-x for x in a)

    def mul(self, a, b):
        out = [0]*(2*self.n-1)
        for j, x in enumerate(a):
            if not x:
                continue
            for k, y in enumerate(b):
                if y:
                    out[j+k] += x*y
        return self.reduce(out)

    def sum(self, vals):
        ans = self.zero
        for val in vals:
            ans = self.add(ans, val)
        return ans

    def conjugate(self, val):
        return self.sum(tuple(x*y for y in self.root(-j)) for j, x in enumerate(val))


def cyclotomic_determinants():
    records = []
    for q in (2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 18, 20, 24, 25, 27, 32, 36, 64):
        ring = Cyclotomic(q)
        coeff = [ring.one]
        # Exact formal identity product_j (1+t*z^j) = 1-(-t)^q.
        for j in range(q):
            nxt = [ring.zero]*(len(coeff)+1)
            for k, c in enumerate(coeff):
                nxt[k] = ring.add(nxt[k], c)
                nxt[k+1] = ring.add(nxt[k+1], ring.mul(c, ring.root(j)))
            coeff = nxt
        expected_last = ring.one if q % 2 else ring.neg(ring.one)
        assert coeff == [ring.one]+[ring.zero]*(q-1)+[expected_last]
        records.append({"q": q, "formal_product_identity_exact": True})
    return records


def W4(d, a, b):
    """Weyl entries for b divisible by d/4, all exactly in Q(i)."""
    assert d % 4 == 0 and b % (d//4) == 0
    mat = sp.zeros(d)
    for j in range(d):
        mat[(j+a) % d, j] = sp.I**((4*b//d*j) % 4)
    return mat


def clean(mat):
    return mat.applyfunc(sp.expand)


def projector_family(d):
    eye, zero = sp.eye(d), sp.zeros(d)
    proj = {}
    raw = 0
    for a, b in product(range(0, d, d//4), repeat=2):
        if (a, b) == (0, 0):
            continue
        op = W4(d, a, b)
        assert op**4 == eye
        if a % (d//2) == 0 and b % (d//2) == 0:
            for sign in (1, -1):
                p = (eye+sign*op)/2
                c = eye+sign*op
                assert c*c.conjugate().T == 4*p
                proj.setdefault(tuple(p), {"kind": "involution", "label": [a, b],
                                           "sign": sign})
                raw += 1
        else:
            for k in range(4):
                p = clean(sum(((sp.I**(-k*t)+sp.I**(-(k+1)*t))*op**t
                               for t in range(4)), zero)/4)
                assert p**2 == p and p.conjugate().T == p and sp.trace(p) == d//2
                c = (op-sp.I**(k+2)*eye)*(op-sp.I**(k+3)*eye)
                assert clean(c*c.conjugate().T-8*p) == zero
                proj.setdefault(tuple(p), {"kind": "adjacent_order4", "label": [a, b],
                                           "first_eigenvalue_power": k})
                raw += 1
    assert raw == 54 and len(proj) == 30
    counts, pairs = Counter(), []
    for (p, desc1), (q, desc2) in combinations(proj.items(), 2):
        inter = d-(sp.Matrix(d, d, p)+sp.Matrix(d, d, q)).to_DM().rank()
        assert inter in (0, d//4), (d, desc1, desc2, inter)
        counts[inter] += 1
        pairs.append({"first": desc1, "second": desc2, "intersection_dimension": inter})
    assert dict(counts) == ({0: 207, 2: 228} if d == 8 else {0: 15, d//4: 420})
    print("projector family", d, dict(counts), flush=True)
    return {"d": d, "raw_factorizations": raw, "distinct_projectors": len(proj),
            "pair_counts": dict(counts), "all_pair_records": pairs}


def rank_thirteen():
    records = []
    cells = []
    for x, y in product(range(4), repeat=2):
        failures = sum(t not in (0, 1) for t in (x, y, (x+y) % 4))
        cells.append({"x": x, "y": y, "failed_conditions": failures})
    zeros = [(c["x"], c["y"]) for c in cells if c["failed_conditions"] == 0]
    assert zeros == [(0, 0), (0, 1), (1, 0)]
    spectrum_counts = Counter(c["failed_conditions"] for c in cells)
    for d in (16, 32):
        eye, zero = sp.eye(d), sp.zeros(d)
        u, v = W4(d, d//4, 0), W4(d, 0, d//4)
        assert u*v == v*u and u**4 == v**4 == eye
        factors = [clean((t-eye)*(t-sp.I*eye)) for t in (u, v, u*v)]
        total = clean(sum((c*c.conjugate().T for c in factors), zero))
        assert total.to_DM().rank() == 13*d//16
        assert sp.trace(total) == 12*d
        assert total.conjugate().T == total
        for c in factors:
            assert c.to_DM().rank() == d//2
        char_checks = 0
        for cell in cells:
            x, y = cell["x"], cell["y"]
            p = clean(sum((sp.I**(-(x*a+y*b))*u**a*v**b
                           for a, b in product(range(4), repeat=2)), zero)/16)
            assert p*p == p and p.conjugate().T == p and sp.trace(p) == d//16
            assert clean(total*p-8*cell["failed_conditions"]*p) == zero
            char_checks += 1
        records.append({"d": d, "rank": 13*d//16, "trace_before_normalizing": 12*d,
                        "constituent_ranks": [d//2]*3,
                        "factor_polynomial": "t^2-(1+i)t+i",
                        "factor_relative_Weyl_labels": [
                            [[0, 0], [d//4, 0], [d//2, 0]],
                            [[0, 0], [0, d//4], [0, d//2]],
                            [[0, 0], [d//4, d//4], [d//2, d//2]]],
                        "joint_projector_checks": char_checks,
                        "nullity_divides_dimension": d % (3*d//16) == 0})
        print("rank thirteen family", d, 13*d//16, flush=True)
    return {"cells": cells, "zero_characters": zeros,
            "eigenvalues_of_unnormalized_sum_divided_by_8": dict(spectrum_counts),
            "matrix_replays": records}


def rank_five_eighths():
    ring = Cyclotomic(8)
    coeff = [ring.one]
    for j in range(3):
        nxt = [ring.zero]*(len(coeff)+1)
        for k, c in enumerate(coeff):
            nxt[k] = ring.add(nxt[k], ring.neg(ring.mul(c, ring.root(j))))
            nxt[k+1] = ring.add(nxt[k+1], c)
        coeff = nxt
    assert len(coeff) == 4 and all(c != ring.zero for c in coeff)
    records = []
    for d in (8, 16, 32, 64):
        vals = [ring.sum(ring.mul(c, ring.root(j*k)) for k, c in enumerate(coeff))
                for j in range(d)]
        zero_indices = [j for j, val in enumerate(vals) if val == ring.zero]
        assert zero_indices == [j for j in range(d) if j % 8 in (0, 1, 2)]
        assert d-len(zero_indices) == 5*d//8
        norm = ring.sum(ring.mul(v, ring.conjugate(v)) for v in vals)
        assert norm == (8*d, 4*d, 0, -4*d)
        records.append({"d": d, "rank": d-len(zero_indices),
                        "exact_sparsity": 4, "zero_indices": zero_indices,
                        "squared_HS_norm_coefficients": norm,
                        "squared_HS_norm_formula": "4*d*(2+sqrt(2))"})
    return {"coefficient_ring": "Z[z]/(z^4+1)", "coefficients": coeff, "cases": records}


def composite_counterexample():
    d = 12
    alpha = sp.root(2, 4)
    u, v = W4(d, 3, 0), W4(d, 0, 3)
    assert u*v == sp.I*v*u and u**4 == v**4 == sp.eye(d)
    c = alpha*sp.eye(d)+u+v
    rank = c.to_DM(extension=True).rank()
    assert rank == 9
    assert subgroup_size(d, (0, 0), (0, 0)) == 1
    return {"d": d, "operator": "2^(1/4) I + X^3 + Z^3",
            "commutator_order": 4, "central_label_subgroup_order": 1,
            "rank": rank, "nullity": d-rank,
            "exact_domain": str(c.to_DM(extension=True).domain),
            "rejected_claim": "Every noncommuting Weyl trinomial has nullity at most two in arbitrary composite dimension."}


def sharpness_scalar_check():
    selected = [j for j in range(4)
                if sp.expand((1-sp.I)*sp.I**j+sp.I*sp.I**(2*j)-1) == 0]
    assert selected == [0, 1]
    return {"d": 8, "U": "X", "V": "X^2*Z^4", "a_squared": "1-i",
            "b_squared": "i", "singular_central_character_powers": selected,
            "nullity_from_exact_block_rule": 2}


def main():
    start = time.monotonic()
    result = {"arithmetic": "integers, Gaussian rationals, integer cyclotomic rings, exact algebraic number fields",
              "status":"PASS",
              "universal_label_arithmetic":universal_arithmetic(),
              "central_arithmetic": central_arithmetic(),
              "formal_cyclic_block_determinants": cyclotomic_determinants(),
              "half_rank_projectors": [projector_family(8), projector_family(16)],
              "rank_thirteen_sixteenths": rank_thirteen(),
              "rank_five_eighths": rank_five_eighths(),
              "non_prime_power_counterexample": composite_counterexample(),
              "noncommuting_bound_sharpness": sharpness_scalar_check(),
              "separate_composite_matrix_checks":composite_checks(),
              "analytic_quantifiers": "All dimensions and arbitrary coefficients are proved in the manuscript, not by these finite tests.",
              "review_scope": "This replay is not independent agent review. Version-specific review reports are separate from this computational certificate.",
              "python_version":platform.python_version(),
              "sympy_version":sp.__version__}
    result["elapsed_seconds"] = time.monotonic()-start
    result["script_sha256"] = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    result["companion_sha256"] = hashlib.sha256(Path(__file__).with_name('composite_matrix_checks.py').read_bytes()).hexdigest()
    result["manuscript_sha256"] = hashlib.sha256(Path(__file__).with_name('quantum_weyl_trinomials.md').read_bytes()).hexdigest()
    dest = Path(__file__).with_name("quantum_weyl_certificate.json")
    dest.write_text(json.dumps(result, indent=2)+"\n", encoding="utf-8")
    print("PASS", dest, "seconds", result["elapsed_seconds"], flush=True)


if __name__ == "__main__":
    main()
