"""Minimum weights, by meet-in-the-middle over column combinations (exact, over F_p; min weight of a
linear code is field-extension invariant, so this is the min weight over any char-p field).
 (R) Radon kernel on F_p^2: functions with zero sum on every affine line.  Claim: min weight = 2p.  p = 2,3,5.
 (N) First-order obstruction code N(p,k) on (Z/p^k)^2: zero sum on every primitive line (coset of a cyclic
     subgroup of order p^k).  Claim: min weight = 2p.  d = 4, 8, 9, 16.
A codeword of weight <= w containing the point 0 (translation invariance) exists iff
   h_0 + sum_{i<=w-1} c_i h_{s_i} = 0,  i.e.  -h_0 - A = A'  for A, A' sums of <= ceil((w-1)/2) scaled columns.
"""
import sys, itertools
from math import gcd

def columns_radon(p):
    pts = [(x, y) for x in range(p) for y in range(p)]
    lines = []
    for m in range(p):            # y = m x + c
        for c in range(p): lines.append({(x, (m*x + c) % p) for x in range(p)})
    for c in range(p):            # x = c
        lines.append({(c, y) for y in range(p)})
    H = {pt: tuple(1 if pt in L else 0 for L in lines) for pt in pts}
    return pts, H

def columns_obstruction(p, k):
    d = p**k
    pts = [(x, y) for x in range(d) for y in range(d)]
    # primitive directions (cyclic subgroups of order d generated by primitive vectors)
    gens = set()
    for a in range(d):
        for b in range(d):
            if a % p and b % p == 0 or b % p and a % p == 0 or (a % p and b % p):
                # normalise generator up to units
                for u in range(1, d):
                    if gcd(u, d) == 1:
                        g = ((u*a) % d, (u*b) % d)
                        if g[0] == 1 or (g[0] % p == 0 and g[1] == 1):
                            gens.add(g); break
    assert len(gens) == p**(k-1)*(p+1), (len(gens), p**(k-1)*(p+1))
    lines = []
    for g in gens:
        sub = {((t*g[0]) % d, (t*g[1]) % d) for t in range(d)}
        seen = set()
        for pt in pts:
            if pt in seen: continue
            L = {((pt[0]+s[0]) % d, (pt[1]+s[1]) % d) for s in sub}
            seen |= L; lines.append(L)
    H = {pt: tuple(1 if pt in L else 0 for L in lines) for pt in pts}
    return pts, H

def min_weight_at_most(pts, H, p, w):
    """return a codeword (dict pt->coef) of weight <= w containing pts[0], or None"""
    h0 = H[pts[0]]
    others = pts[1:]
    half = (w - 1 + 1) // 2  # ceil((w-1)/2)
    n = len(h0)
    units = list(range(1, p))
    def sums(maxk):
        table = {}
        table[tuple([0]*n)] = ()
        for kk in range(1, maxk+1):
            for combo in itertools.combinations(others, kk):
                for coefs in itertools.product(units, repeat=kk):
                    v = [0]*n
                    for pt, c in zip(combo, coefs):
                        hv = H[pt]
                        for i in range(n):
                            if hv[i]: v[i] = (v[i] + c*hv[i]) % p
                    table.setdefault(tuple(v), tuple(zip(combo, coefs)))
        return table
    A = sums(half)
    B = A if 2*half >= w-1 else None
    other_half = (w-1) - half
    Bt = sums(other_half) if other_half != half else A
    for v, combo in A.items():
        need = tuple((-h0[i] - v[i]) % p for i in range(n))
        if need in Bt:
            word = {pts[0]: 1}
            for pt, c in combo: word[pt] = (word.get(pt, 0) + c) % p
            for pt, c in Bt[need]: word[pt] = (word.get(pt, 0) + c) % p
            word = {pt: c for pt, c in word.items() if c}
            # verify
            tot = [0]*n
            for pt, c in word.items():
                for i in range(n): tot[i] = (tot[i] + c*H[pt][i]) % p
            assert not any(tot)
            return word
    return None

if __name__ == "__main__":
    for p in (2, 3, 5):
        pts, H = columns_radon(p)
        wmax = 2*p - 1
        word = min_weight_at_most(pts, H, p, wmax)
        # also confirm weight 2p exists: two parallel lines
        print(f"(R) Radon kernel on F_{p}^2: codeword of weight <= {wmax}: {word}")
    for (p, k) in ((2, 2), (2, 3), (3, 2), (2, 4)):
        pts, H = columns_obstruction(p, k)
        wmax = 2*p - 1
        word = min_weight_at_most(pts, H, p, wmax)
        print(f"(N) obstruction code d={p**k}: #primitive lines={len(H[pts[0]])}; codeword of weight <= {wmax}: {word}")
